#!/bin/bash

# Chemin

show_path(){
  echo ""
  while IFS= read -r line;do
      [[ "$line" == \#* ]] && continue
      [[ -z "$line" ]] && continue
      echo "$line"
  done < "$config_file"
  echo ""
  exit 0
}

# HELP

show_help(){
    echo ""
    echo "Usage: lwatcher [OPTIONS] [PATH]"
    echo ""
    echo "Options:"
    echo "  -h          Display this manual"
    echo "  -s          Display the monitored directories"
    echo "  -D          Delete the list of directories to monitor"
    echo "  -d n        Set the maximum number of days to store backups (default: 7)"
    echo "  -c PATH     Add a new directory to monitor and then run the program"
    echo "  -C PATH     Delete the list of directories to monitor and add a new directory to monitor, then run the program"
    echo "  -a          Add a new directory to monitor (without running the program)"
    echo "  -n          Skip creating the backup archive (temporary files needed for diffs are still created and then deleted at the end of the session)"
    echo ""
    echo "Examples:"
    echo "  lwatcher"
    echo "  lwatcher -d 14"
    echo "  lwatcher -c /etc/lwatcher/inotify.conf"
    echo "  lwatcher -d 30 -c /etc/lwatcher/inotify.conf"
    echo ""
    exit 0
}

RED="\033[31m"
GREEN="\033[32m"
YELLOW="\033[33m"
BLUE="\033[34m"
PURPLE="\033[35m"
CYAN="\033[36m"
RESET="\033[0m"

session_time=$(date +%Y%m%d_%H%M)
max_days=7
config_file="/etc/lwatcher/inotify.config"
skip_backup=0

if [ "$EUID" -ne 0 ];then
    printf "${YELLOW}Warning:${RESET} L-watcher must be executed as root"
    exit 5
fi

if [ ! -f "/opt/lwatcher/bin/inotify" ] || [ ! -f "/opt/lwatcher/scripts/cleanup.sh" ] || [ ! -f "/opt/lwatcher/scripts/backup.sh" ] ||[ ! -f "/opt/lwatcher/scripts/output.sh" ];then
    echo -e "${RED}Error:${RED} Executable File missing"
    exit 2
fi



if [ ! -f "$config_file" ];then
    printf "${RED}Error:${RESET} file /etc/lwatcher/inotify.config missing"
    exit 2
fi


log_dir="/var/log/lwatcher"
log_file="$log_dir/session.log"

if [ ! -d "$log_dir" ]; then
    mkdir $log_dir
fi

touch $log_file

while getopts "hsDd:c:C:a:r:n" opt; do
    case $opt in
        h) show_help ;;
        s) show_path ;;
        D) echo -n "" > "$config_file"
           exit 0
           ;;
        d) max_days=$OPTARG ;;
        c) new_path=$OPTARG
            if [[ -n "$new_path" ]];then
                echo "$new_path" >> "$config_file"
            fi
            ;;
        C) new_path=$OPTARG
           if [[ -n "$new_path" ]];then
              echo "$new_path" > "$config_file"
           fi
           ;;
        a) new_path=$OPTARG
            if [[ -n "$new_path" ]];then
                echo "$new_path" >> "$config_file"
            fi
            exit 0
            ;;
        n) skip_backup=1 ;;
        ?) echo "Unknown option"; exit 1 ;;
    esac
done

if [ ! -s "$config_file" ];then
  printf "${RED}Error:${RESET} Fichier de configuration vide"
  exit 2
fi

{
trap "/opt/lwatcher/scripts/cleanup.sh $session_time $max_days $remote_backup" EXIT
/opt/lwatcher/scripts/backup.sh "$session_time" "$remote_backup" "$skip_backup"
/opt/lwatcher/bin/inotify | /opt/lwatcher/scripts/output.sh "$session_time"
} 2>> "/var/log/lwatcher/error.log"
