#!/bin/bash

# Chemin

show_path(){
  echo ""
  while IFS= read -r line;do
      [[ "$line" == \#* ]] && continue
      [[ -z "$line" ]] && continue
      echo "$line"
  done < "$config_file"
  echo ""
  exit 0
}

# HELP

show_help(){
    echo ""
    echo "Usage: lwatcher [OPTIONS] [CHEMIN]"
    echo ""
    echo "Options:"
    echo "  -h          Afficher cette manuel"
    echo "  -s          Afficher les repertoires surveillés"
    echo "  -D          Supprime la liste des repertoires à surveiller"
    echo "  -d n        Définir le nombre de jour maximum pour stocker les sauvegardes (par defaut: 7)"
    echo "  -c CHEMIN   Ajouter un nouvel repertoire à surveiller puis lancer le programme"
    echo "  -C CHEMIN   Supprime la liste des repertoires à surveiller et ajouter un nouvel repertoire à surveiller puis lance le programme"
    echo "  -a          Ajoute un nouvel repertoire à surveiller (sans lancer le programme)"
    echo "  -r ADMIN    Copie les archives de sauvegardes vers un autre pc (fonctionne avec sshd uniquement)"
    echo ""
    echo "Exemples:"
    echo "  lwatcher"
    echo "  lwatcher -d 14"
    echo "  lwatcher -c /etc/lwatcher/inotify.conf"
    echo "  lwatcher -d 30 -c /etc/lwatcher/inotify.conf"
    echo "  lwatcher -r user@192.169.1.2:/chemin/sauvegarde"
    echo ""
    exit 0
}

# Couleur

RED="\033[31m"
GREEN="\033[32m"
YELLOW="\033[33m"
BLUE="\033[34m"
PURPLE="\033[35m"
CYAN="\033[36m"
RESET="\033[0m"

session_time=$(date +%Y%m%d_%H%M) # Synchronisation des dates
max_days=7 # MAximum de jour par defaut
config_file="/etc/lwatcher/inotify.config" # Chemin du fichier de configuration


# Verification du fichier binaire
if [ ! -f "/opt/lwatcher/bin/inotify" ];then
    echo "Fichier bin inotify absent"
    exit 0
fi

if [ ! -f "/opt/lwatcher/scripts/cleanup.sh" ];then
    echo "Fichier scripts cleanup.sh absent"
    exit 0
fi

if [ ! -f "/opt/lwatcher/scripts/backup.sh" ];then
    echo "Fichier scripts backup.sh absent"
    exit 0
fi

if [ ! -f "/opt/lwatcher/scripts/output.sh" ];then
    echo "Fichier scripts output.sh absent"
    exit 0
fi

# Verification du fichier de configuration
if [ ! -f "$config_file" ];then 
    printf "${RED}Error:${RESET} ficher /etc/lwatcher/inotify.config absent"
    exit 0
fi

if [ "$EUID" -ne 0 ];then
    printf "${YELLOW}Warning:${RESET} Le script n'est pas executer en tant que root"
fi

log_dir="/var/log/lwatcher"
log_file="$log_dir/session.log"

if [ ! -d "$log_dir" ]; then
    mkdir $log_dir
fi

touch $log_file

# Gestion des options

while getopts "hsDd:c:C:a:r:" opt; do
    case $opt in
        h) show_help ;;
        s) show_path ;;
        D) echo -n "" > "$config_file"
           exit 0
           ;;
        d) max_days=$OPTARG ;;
        c) new_path=$OPTARG
            if [[ -n "$new_path" ]];then
                echo "$new_path" >> "$config_file"
            fi
            ;;
        C) new_path=$OPTARG
           if [[ -n "$new_path" ]];then
              echo "$new_path" > "$config_file"
           fi
           ;;
        a) new_path=$OPTARG
            if [[ -n "$new_path" ]];then
                echo "$new_path" >> "$config_file"
            fi
            exit 0
            ;;
        r) remote_backup=$OPTARG;;
        ?) echo "Option inconnue, lwatcher -h pour afficher l'aide."; exit 1 ;;
    esac
done

if [ -n "$remote_backup" ]; then
    ssh-keygen -t ed25519 -f ~/.ssh/lwatch_key -N ""
    ssh-copy-id -i ~/.ssh/lwatch_key.pub "${remote_backup%%:*}"
fi

{
trap "/opt/lwatcher/scripts/cleanup.sh $session_time $max_days $remote_backup" EXIT
/opt/lwatcher/scripts/backup.sh "$session_time" "$remote_backup"
/opt/lwatcher/bin/inotify | /opt/lwatcher/scripts/output.sh "$session_time"
} 2>> "/var/log/lwatcher/error.log"